<a href="https://colab.research.google.com/github/Manawariqbal/Data-science-code/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy
"""

Numpy:Python library which is used for numerical computation
"""



'\n\nNumpy:Python library which is used for numerical computation\n'

In [2]:
import numpy as np

#Difference between array and list

lst=[1,2,3,4,5]

#Memory location 1=1000,2=2000,3=3000,3=1015



#Memory
#1,=1000,2=1004,3=1008,4=1012


#properties of numpy
#ndarray object
#Vectorized operation :Perform element wise calculation without using loop
#Linear Algebra Function :inversion of matrix
#Broadcasting:Operate on arrays of different shapes
#statistical function =mean,median,standard deviation
#Integration:Works with pandas,scikit learn


"""
Matrix=1,2
       2,1
       [[1,2],[2,1]]
"""








'\nMatrix=1,2\n       2,1\n       [[1,2],[2,1]]\n'

In [3]:
matrix=[[1,2],[2,1]]
matrix

[[1, 2], [2, 1]]

In [4]:
#Basic

import numpy as np

#numpy arrays
lst=[1,2,3,4]
a1=np.array(lst)
# 1D array
a1=np.array([1,2,3,4])

#2D array

a2=np.array([[1,2],[3,4]])
a2=np.array(matrix)
a2
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])



In [5]:
#using numpy function


a0=np.zeros((3,3))
a0
a1=np.ones((2,2))
a1



array([[1., 1.],
       [1., 1.]])

In [6]:
#Numpy Array access
#using index

a1=np.array([10,20,30,40,50])
print(a1[0])
print(a1[-1])
print(a2[0][0])


10
50
1


In [7]:
#using slicing

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#row wise slicing
print(a[1:3])

[[4 5 6]
 [7 8 9]]


In [8]:
#Basic Arithmatic operation


x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x**y)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]


In [9]:
import numpy as np



number=[1,9,0,2,8,7,6]


type(number)


#How to convert a list to array

number=np.array(number)

type(number)


#Task create an array of all even number from 1 to 10


even=[2,4,6,8,10]
even=np.array(even)
even





array([ 2,  4,  6,  8, 10])

In [10]:
odd=np.array([1,3,5,7,9])
odd


"""
1,2,3
4,5,6
7,8,9

"""

matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix[1][1]
matrix[2][0]
matrix

matrix=np.array(matrix)

matrix

a2=np.array([[1,2],[3,4]])

a2



array([[1, 2],
       [3, 4]])

In [11]:
#other method to create arrays


a=np.zeros((2, 3)) # all zeros




a

#create a matrix with zeros with 5 rows and 3 columns
np.zeros((5,3))



np.ones((4,4))




array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#Accessing an array

number=[1,2,3,4,5]
number=np.array(number)
print(number[4])

print(number[1])







5
2


In [13]:
#Accessing 2d Array
lst=[[1,2,3],[4,5,6],[7,8,9]]
#nested list

lst=[1,2,3,4]
lst=[[1,2],[3,4],[5,6]]
lst[0][1]


lst[2][0]


#sum all the element of this list lst=[1,2,3,4]
lst=[[1,2],[3,4],[5,6]]


sum=0
for i in range(len(lst)):
  for j in range(len(lst[0])):
    sum=sum+lst[i][j]

print(sum)



21


In [14]:
#indexing 2d array

array=np.array(lst)


array


print(array[2][1])

print(array[0,1])







6
2


In [15]:
arr=np.array([3,4,5,6,7,9,1,0])
arr

#slicing
#syntax arr[startpoint:endpoint:stepfunction]




print(arr[5:])

print(arr[::-1])



#even index element



[9 1 0]
[0 1 9 7 6 5 4 3]


In [16]:



"""

number=[5,6,7,9,1,3,10,20,-1,3]

        0,1,2,3,4,5,6,7,8,9,
"""

number=[5,6,7,9,1,3,10,20,-1,3]
print(number[0:3])
print(number[:5])



#even number
print(number[0:10:2])

[5, 6, 7]
[5, 6, 7, 9, 1]
[5, 7, 1, 10, -1]


In [17]:
#Basic Arithmatic operations
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y) #add
print(x-y) #sub
print(x*y) #mul
print(x/y) #divisible

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
#absolute
a=np.array([-3,-1,1,2,-4])
print(np.absolute(a))



[3 1 1 2 4]


In [19]:
#Binary operators
x
y

result=np.add(x,y)

result
print(np.subtract(x,y))
x

print(np.sqrt(x))



[-3 -3 -3]
[1.         1.41421356 1.73205081]


In [20]:
#sorting

a=np.array([4,1,2,7,1,0])
a=np.sort(a)
a


array([0, 1, 1, 2, 4, 7])

In [21]:
#. arange(), linspace(), and logspace()

a=np.arange(0, 101, 10)
a

a=np.linspace(0,1,5)

a

#8=2^3

a=np.logspace(1, 3, 3)

a

array([  10.,  100., 1000.])

In [22]:
#NumPy Array Attributes

a=np.array([1,2,3,4,5,6,7,8])
b=np.array([[1,2],[2,3]])
#Dimension

a.ndim
b.ndim




#shape= Size along each dimension
"""

1,2,3
3,4,6    2*3
3,4,2


"""

matrix=np.array([[1,2,3],[2,3,4],[4,7,8],[1,2,3]])
b.shape
matrix.shape


matrix.shape


#size
matrix.size
a.size

"""
matrix=1,2,3
       2,3,4


       1,2
       2,1

       2*2



"""
#dtype
a.dtype


#
a.itemsize

8

In [23]:
#Type conversion
arr=np.array([2.3,3.4,6.5])

arr.dtype

integer=arr.astype(int)
integer.dtype

#small task
array=np.array([1,2,3,4])
array.dtype

#arr to float
Float=array.astype(float)
Float.dtype

dtype('float64')

In [24]:
#reshape() changes the dimensions without changing the number of elements.
#1 dimension to multi dimension

arr=np.array([1,2,3,4,6,7,1,2,3,5,7,8])
arr.shape

arr.reshape(3,4)
arr.reshape(2,3,2)



#flatten
#multi dimension to 1 dimension


arr.flatten()
arr.ravel()





array([1, 2, 3, 4, 6, 7, 1, 2, 3, 5, 7, 8])

In [25]:
# Create a 3×3 array containing zeros.
np.zeros((3,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#Given an array of student marks, calculate mean, median, standard deviation, minimum, and maximum.

marks=np.array([80,98,72,34,67,89,76,67,90,78,89])

marks

#mean
print("Mean=: ",marks.mean())

#median
print("Median: ",np.median(marks))


#standard deviation

print("Standard deviation: ",np.std(marks))


#minimum
print("Minimum",np.min(marks))


#maximum
print("Maximum ",np.max(marks))

Mean=:  76.36363636363636
Median:  78.0
Standard deviation:  16.45529882755498
Minimum 34
Maximum  98


In [38]:
#Join array
a=np.array([1,2,3,1])
b=np.array([7,9,8,9])
d=np.array([2,8,0,9])
c=np.concatenate((a,b,d))
c

array([1, 2, 3, 1, 7, 9, 8, 9, 2, 8, 0, 9])

In [42]:
c
np.split(c,6)

[array([1, 2]),
 array([3, 1]),
 array([7, 9]),
 array([8, 9]),
 array([2, 8]),
 array([0, 9])]

In [56]:
lst=[1,2,3,9,8,10,6]



#vectorization
arr=np.array(lst)
arr=arr*arr
arr
matrix=np.array([[1,2,3],[4,5,6]])
matrix
matrix=matrix+10
matrix

array([[11, 12, 13],
       [14, 15, 16]])

In [65]:
#Arithmatic operation
a=np.array([1,2,3,4])
b=np.array([9,0,7,3])
matrix
c=a*b

c

array([ 9,  0, 21, 12])

In [63]:
matrix=np.array([[1,2,3],[4,5,6]])
matric=np.array([[4,8,7],[1,4,6]])
new_matrix=matrix*matric
new_matrix



array([[ 4, 16, 21],
       [ 4, 20, 36]])

In [67]:
#broadcasting
a=np.array([1,2,3])
b=10 #([10,10,10])
result=a+b
result


array([11, 12, 13])

In [76]:
a=np.array([1,2,3])
matrix=np.array([[1,2,3],[3,4,5]])#a [[1,2,3],[1,2,3]
#print(a+matrix)

a
matrix
new_matrix=a+matrix
print(new_matrix)


[[2 4 6]
 [4 6 8]]


In [78]:
#Aggregiation


data = np.array([10, 20, 30, 40, 50])
print(np.sum(data))
print(np.mean(data))
print(np.median(data))
print(np.min(data))
print(np.max(data))
print(np.std(data))


150
30.0
30.0
10
50
14.142135623730951


In [90]:
#axis axis=0 columns axis=1 row
matrix=np.array([[1,2,3],[4,5,6],[4,9,0],[1,7,0],[0,-1,4],[1,2,4]])
matrix
#print(np.sum(matrix,axis=1))
#maximum values in each row
#print(np.max(matrix,axis=1))

matrix.shape

print(np.max(matrix,axis=1))
print(np.max(matrix,axis=0))
matrix

[3 6 9 7 4 4]
[4 9 6]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  9,  0],
       [ 1,  7,  0],
       [ 0, -1,  4],
       [ 1,  2,  4]])